name: Code Analysis

on:
    pull_request: null
    push: null

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: "PHPStan and PHPUnit"
                        run: bin/test

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   run: bin/install
            -   run: ${{ matrix.actions.run }}
